services:
  apache:
    build:
      context: ./docker/apache
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    volumes:
      - ./www:/var/www/html
    environment:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
