services:
  apache-ssl:
    build: .
    container_name: apache-ssl
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      # Опционально: монтируем свой сайт
      - ./www:/var/www/localhost/htdocs

